--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-09-2024
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PHOTO_TBL
--------------------------------------------------------
  CREATE TABLE "FOODTEAM2"."PHOTO_TBL"
   (	"BOARD_NUM" NUMBER DEFAULT 0,
	"BOARD_WRITER" VARCHAR2(30 BYTE),
	"BOARD_PASS" VARCHAR2(20 BYTE),
	"BOARD_SUBJECT" VARCHAR2(100 BYTE),
	"BOARD_CONTENT" VARCHAR2(4000 BYTE),
	"BOARD_RE_REF" NUMBER,
	"BOARD_RE_LEV" NUMBER,
	"BOARD_RE_SEQ" NUMBER,
	"BOARD_READCOUNT" NUMBER DEFAULT 0,
	"BOARD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FOODTEAM2.PHOTO_TBL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "FOODTEAM2"."TABLE1_PK" ON "FOODTEAM2"."PHOTO_TBL" ("BOARD_NUM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PHOTO_TBL
--------------------------------------------------------
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("BOARD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" MODIFY ("BOARD_RE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" MODIFY ("BOARD_RE_LEV" NOT NULL ENABLE);
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" MODIFY ("BOARD_RE_REF" NOT NULL ENABLE);
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" MODIFY ("BOARD_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" MODIFY ("BOARD_PASS" NOT NULL ENABLE);
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" MODIFY ("BOARD_WRITER" NOT NULL ENABLE);
  ALTER TABLE "FOODTEAM2"."PHOTO_TBL" MODIFY ("BOARD_NUM" NOT NULL ENABLE);


CREATE SEQUENCE photo_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE;
​

-- 테이블 PK 시퀀스
CREATE SEQUENCE image_upload_file_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE;


CREATE TABLE upload_file_tbl (
	id number(10,0) primary key,
	filename nvarchar2(300) not null,
	save_filename nvarchar2(500) not null,
	file_path nvarchar2(500) not null,
	content_type nvarchar2(10),
	file_size number(20,0) default 0,
	regdate date default sysdate
);




