--음식유형이 1번이 것의 이름과 타입번호를 가져옴 
SELECT *
FROM FOOD_CATE_CODE_TBL C, FOOD_TBL F
WHERE C.FOOD_CODE = F.FOOD_CODE  AND C.FOOD_CATE_CODE = 4 ;



--음식 유형 개수
SELECT count(*)
FROM FOOD_CATE_CODE_TBL C, FOOD_TBL F
WHERE C.FOOD_CODE = F.FOOD_CODE  AND C.FOOD_CATE_CODE = 4 ;



--음식 유형 페이징
SELECT F.FOOD_CODE, F.FOOD_NAME, F.FOOD_IMG, F.FOOD_INTRODUCE,
       F.FOOD_DATE, F.FOOD_DISPLAY, F.FOOD_IMG_ORIGIN, F.FOOD_INGREDIENT_MAIN_INSIDE,
       F.FOOD_INGREDIENT_MAIN_VIEW, F.FOOD_INGREDIENT_SUB_INSIDE, F.FOOD_INGREDIENT_SUB_VIEW, F.FOOD_RECIPE
FROM(
    SELECT M.*, floor((ROWNUM - 1) / 20 + 1) PAGE
    FROM (
        SELECT F.FOOD_CODE, F.FOOD_NAME, F.FOOD_IMG, F.FOOD_INTRODUCE,
               F.FOOD_DATE, F.FOOD_DISPLAY, F.FOOD_IMG_ORIGIN, F.FOOD_INGREDIENT_MAIN_INSIDE,
               F.FOOD_INGREDIENT_MAIN_VIEW, F.FOOD_INGREDIENT_SUB_INSIDE, F.FOOD_INGREDIENT_SUB_VIEW, F.FOOD_RECIPE
        FROM food_cate_code_tbl C 
        JOIN food_tbl F ON C.food_code = F.food_code
        WHERE C.food_cate_code = 4 
    ) M
)F
WHERE PAGE = 2;

