--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-30-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QNA_TBL
--------------------------------------------------------

  CREATE TABLE "FOODTEAM2"."QNA_TBL" 
   (	"QNA_CODE" NUMBER DEFAULT 0, 
	"MEMBER_EMAIL" VARCHAR2(50 BYTE), 
	"MEMBER_NICK" VARCHAR2(50 BYTE), 
	"QNA_TITLE" VARCHAR2(100 CHAR), 
	"QNA_CONTENT" VARCHAR2(4000 BYTE), 
	"QNA_DATE" DATE, 
	"QNA_LOCK_YESNO" NUMBER DEFAULT 0, 
	"QNA_ORIGINAL_FILE" NVARCHAR2(200), 
	"QNA_FILE" NVARCHAR2(200), 
	"QNA_RE_REF" NUMBER, 
	"QNA_RE_LEV" NUMBER, 
	"QNA_RE_SEQ" NUMBER, 
	"QNA_READCOUNT" NUMBER DEFAULT 0, 
	"QNA_IMG" NVARCHAR2(200), 
	"QNA_IMG_ORIGIN" NVARCHAR2(200), 
	"QNA_PASS" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_CODE" IS '글번호';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."MEMBER_EMAIL" IS '회원이메일';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."MEMBER_NICK" IS '회원닉네임';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_TITLE" IS '게시글 제목';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_CONTENT" IS '게시글 내용';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_DATE" IS '게시글 날짜';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_LOCK_YESNO" IS '게시글 잠금여부';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_ORIGINAL_FILE" IS '첨부파일원본';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_FILE" IS '첨부파일';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_RE_REF" IS '댓글';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_RE_LEV" IS '댓글계층';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_RE_SEQ" IS '댓글순서';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_READCOUNT" IS '조회수';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_IMG" IS '삽입이미지';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_IMG_ORIGIN" IS '삽입이미지 원본';
   COMMENT ON COLUMN "FOODTEAM2"."QNA_TBL"."QNA_PASS" IS '게시글 패스워드';
